coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 1%
    patch:
      default:
        target: 60%

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: bot
      paths:
        - apps/bot/
    - name: web
      paths:
        - apps/web/

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false