name: Checks

on:
  workflow_call:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.30.2
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22.22.0
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
      - name: Build
        run: pnpm run build
