name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '24.13.1'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Test
        run: pnpm run test:coverage

      - name: Upload api coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./apps/bot/coverage/lcov.info
          flags: bot
          name: bot-coverage
          fail_ci_if_error: true

      - name: Upload ui coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./apps/web/coverage/lcov.info
          flags: web
          name: web-coverage
          fail_ci_if_error: true